---
title: "NBA 2 vs 3 pointers"
author: "Chris Bryden"
date: "4/20/2021"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(reshape2)
library(VGAM)
library(readr)
```


### Kevin Durant

```{r}
kd <- function(number_of_shots){

shot2 <- c(2, 0)
shot3 <- c(3, 0)

number_of_shots <- number_of_shots

kd2_prob <- c(0.576, 0.424)
kd3_prob <- c(0.448, 0.552)


kd2samp <- sample(shot2, size = number_of_shots, replace = TRUE, prob = kd2_prob)
kd3samp <- sample(shot3, size = number_of_shots, replace = TRUE, prob = kd3_prob)

kd2cumulative <- cumsum(kd2samp)
kd3cumulative <- cumsum(kd3samp)

#kd2cumulative
#kd3cumulative

shot_attempt <- seq(1, number_of_shots, by = 1)

kd2MaxPoints <- max(kd2cumulative)
kd3MaxPoints <- max(kd3cumulative)

kd2PointsPerShot <- max(kd2cumulative)/number_of_shots
kd3PointsPerShot <-max(kd3cumulative) / number_of_shots

kd_df <- data.frame(shot_attempt, kd2cumulative, kd3cumulative)
#kd_df

kd_plot <- ggplot()+
  geom_line(data = kd_df, aes(x = shot_attempt, 
                              y = kd2cumulative,
                              col = "2 point")) +
  geom_line(data = kd_df, aes(x = shot_attempt,
                              y = kd3cumulative,
                              col = "3 point")) +
  labs(title = "Kevin Durant 2 Pointer v. 3 Pointer",
       subtitle = "By 2020-21 Shooting Percentages",
       y = "Points Scored",
       x = "Shots Attempted") +
  theme_minimal()




cat("Kevin Durant would score", kd2MaxPoints, " points by 2 pointers only, and ", kd3MaxPoints, " points from 3 pointers only, based on  ", number_of_shots, "simmulated shot attempts. While averaging,", kd2PointsPerShot, "on 2 pointers, and", kd3PointsPerShot,"on 3 pointers.")

# cat("Based on ", number_of_shots,"simulated shots, Kevin Durant would average", kd2PointsPerShot, "points per shot taking only 2 pointers, and ", kd3PointsPerShot," points per shot taking only 3 pointers.")

kd_plot
}

kd(100)
kd(200)
kd(500)
kd(1000)
kd(10000)
kd(100000)




```

### Steph Curry

```{r}

steph <- function(number_of_shots){

shot2 <- c(2, 0)
shot3 <- c(3, 0)

number_of_shots <- number_of_shots

steph2_prob <- c(0.58, 0.42)
steph3_prob <- c(0.422, 0.578)


steph2samp <- sample(shot2, size = number_of_shots, replace = TRUE, prob = steph2_prob)
steph3samp <- sample(shot3, size = number_of_shots, replace = TRUE, prob = steph3_prob)

steph2cumulative <- cumsum(steph2samp)
steph3cumulative <- cumsum(steph3samp)

# steph2cumulative
# steph3cumulative

shot_attempt <- seq(1, number_of_shots, by = 1)

steph2MaxPoints <- max(steph2cumulative)
steph3MaxPoints <- max(steph3cumulative)

steph2PointsPerShot <- max(steph2cumulative)/number_of_shots
steph3PointsPerShot <-max(steph3cumulative) / number_of_shots

steph_df <- data.frame(shot_attempt, steph2cumulative, steph3cumulative)
#steph_df

steph_plot <- ggplot()+
  geom_line(data = steph_df, aes(x = shot_attempt, 
                              y = steph2cumulative,
                              col = "2 point")) +
  geom_line(data = steph_df, aes(x = shot_attempt,
                              y = steph3cumulative,
                              col = "3 point")) +
  labs(title = "Steph Curry 2 Pointer v. 3 Pointer",
       subtitle = "By 2020-21 Shooting Percentages",
       y = "Points Scored",
       x = "Shots Attempted") +
  theme_minimal()
  
cat("Steph Curry would score", steph2MaxPoints, " points by 2 pointers only, and ", steph3MaxPoints, " points from 3 pointers only, based on  ", number_of_shots, "simmulated shot attempts. While averaging,", steph2PointsPerShot, "on 2 pointers, and", steph3PointsPerShot,"on 3 pointers.")

steph_plot

}
steph(100)
steph(200)
steph(500)
steph(1000)
steph(10000)
steph(100000)
```

### Damian Lillard


```{r}
dame <- function(number_of_shots){
shot2 <- c(2, 0)
shot3 <- c(3, 0)

number_of_shots <- number_of_shots

dame2_prob <- c(0.51, 0.49)
dame3_prob <- c(0.379, 0.621)


dame2samp <- sample(shot2, size = number_of_shots, replace = TRUE, prob = dame2_prob)
dame3samp <- sample(shot3, size = number_of_shots, replace = TRUE, prob = dame3_prob)

dame2cumulative <- cumsum(dame2samp)
dame3cumulative <- cumsum(dame3samp)

# dame2cumulative
# dame3cumulative

shot_attempt <- seq(1, number_of_shots, by = 1)

dame2MaxPoints <- max(dame2cumulative)
dame3MaxPoints <- max(dame3cumulative)

dame2PointsPerShot <- max(dame2cumulative)/number_of_shots
dame3PointsPerShot <-max(dame3cumulative) / number_of_shots

dame_df <- data.frame(shot_attempt, dame2cumulative, dame3cumulative)
#dame_df

dame_plot <- ggplot()+
  geom_line(data = dame_df, aes(x = shot_attempt, 
                              y = dame2cumulative,
                              col = "2 point")) +
  geom_line(data = dame_df, aes(x = shot_attempt,
                              y = dame3cumulative,
                              col = "3 point")) +
  labs(title = "Damian Lillard 2 Pointer v. 3 Pointer",
       subtitle = "By 2020-21 Shooting Percentages",
       y = "Points Scored",
       x = "Shots Attempted") +
  theme_minimal()

cat("Damian Lillard would score", dame2MaxPoints, " points by 2 pointers only, and ", dame3MaxPoints, " points from 3 pointers only, based on  ", number_of_shots, "simmulated shot attempts. While averaging,", dame2PointsPerShot, "on 2 pointers, and", dame3PointsPerShot,"on 3 pointers.")
  
dame_plot
}

dame(100)
dame(200)
dame(500)
dame(1000)
dame(10000)
dame(100000)
```



```{r}
lebron <- function(number_of_shots){

shot2 <- c(2, 0)
shot3 <- c(3, 0)

number_of_shots <- number_of_shots

lebron2_prob <- c(0.592, 0.408)
lebron3_prob <- c(0.386, 0.614)


lebron2samp <- sample(shot2, size = number_of_shots, replace = TRUE, prob = lebron2_prob)
lebron3samp <- sample(shot3, size = number_of_shots, replace = TRUE, prob = lebron3_prob)

lebron2cumulative <- cumsum(lebron2samp)
lebron3cumulative <- cumsum(lebron3samp)

# lebron2cumulative
# lebron3cumulative

shot_attempt <- seq(1, number_of_shots, by = 1)

lebron2MaxPoints <- max(lebron2cumulative)
lebron3MaxPoints <- max(lebron3cumulative)

lebron2PointsPerShot <- max(lebron2cumulative)/number_of_shots
lebron3PointsPerShot <-max(lebron3cumulative) / number_of_shots

lebron_df <- data.frame(shot_attempt, lebron2cumulative, lebron3cumulative)
#lebron_df

lebron_plot <- ggplot()+
  geom_line(data = lebron_df, aes(x = shot_attempt, 
                              y = lebron2cumulative,
                              col = "2 point")) +
  geom_line(data = lebron_df, aes(x = shot_attempt,
                              y = lebron3cumulative,
                              col = "3 point")) +
  labs(title = "Lebron James 2 Pointer v. 3 Pointer",
       subtitle = "By 2020-21 Shooting Percentages",
       y = "Points Scored",
       x = "Shots Attempted") +
  theme_minimal()

 

lebron_plot
}

lebron(100)
lebron(200)
lebron(500)
lebron(1000)
lebron(10000)
lebron(100000)
```

### Saddiq Bey

```{r}
saddiq <- function(number_of_shots){

shot2 <- c(2, 0)
shot3 <- c(3, 0)

number_of_shots <- number_of_shots

saddiq2_prob <- c(0.473, 0.527)
saddiq3_prob <- c(0.386, 0.614)


saddiq2samp <- sample(shot2, size = number_of_shots, replace = TRUE, prob = saddiq2_prob)
saddiq3samp <- sample(shot3, size = number_of_shots, replace = TRUE, prob = saddiq3_prob)

saddiq2cumulative <- cumsum(saddiq2samp)
saddiq3cumulative <- cumsum(saddiq3samp)

# saddiq2cumulative
# saddiq3cumulative

shot_attempt <- seq(1, number_of_shots, by = 1)


saddiq2MaxPoints <- max(saddiq2cumulative)
saddiqMaxPoints <- max(saddiq3cumulative)

saddiq2PointsPerShot <- max(saddiq2cumulative)/number_of_shots
saddiq3PointsPerShot <-max(saddiq3cumulative) / number_of_shots

saddiq_df <- data.frame(shot_attempt, saddiq2cumulative, saddiq3cumulative)
#lebron_df

saddiq_plot <- ggplot()+
  geom_line(data = saddiq_df, aes(x = shot_attempt, 
                              y = saddiq2cumulative,
                              col = "2 point")) +
  geom_line(data = saddiq_df, aes(x = shot_attempt,
                              y = saddiq3cumulative,
                              col = "3 point")) +
  labs(title = "Saddiq Bey 2 Pointer v. 3 Pointer",
       subtitle = "By 2020-21 Shooting Percentages",
       y = "Points Scored",
       x = "Shots Attempted") +
  theme_minimal()
  


saddiq_plot
}

saddiq(100)
saddiq(200)
saddiq(500)
saddiq(1000)
saddiq(10000)
saddiq(100000)
```

### James Harden

```{r}
harden <- function(number_of_shots){

shot2 <- c(2, 0)
shot3 <- c(3, 0)

number_of_shots <- number_of_shots

harden2_prob <- c(0.548, 0.452)
harden3_prob <- c(0.361, 0.639)


harden2samp <- sample(shot2, size = number_of_shots, replace = TRUE, prob = harden2_prob)
harden3samp <- sample(shot3, size = number_of_shots, replace = TRUE, prob = harden3_prob)

harden2cumulative <- cumsum(harden2samp)
harden3cumulative <- cumsum(harden3samp)

# harden2cumulative
# harden3cumulative

shot_attempt <- seq(1, number_of_shots, by = 1)

harden2MaxPoints <- max(harden2cumulative)
harden3MaxPoints <- max(harden3cumulative)

harden2PointsPerShot <- max(harden2cumulative)/number_of_shots
harden3PointsPerShot <-max(harden3cumulative) / number_of_shots

harden_df <- data.frame(shot_attempt, harden2cumulative, harden3cumulative)
#harden_df

harden_plot <- ggplot()+
  geom_line(data = harden_df, aes(x = shot_attempt, 
                              y = harden2cumulative,
                              col = "2 point")) +
  geom_line(data = harden_df, aes(x = shot_attempt,
                              y = harden3cumulative,
                              col = "3 point")) +
  labs(title = "James Harden 2 Pointer v. 3 Pointer",
       subtitle = "By 2020-21 Shooting Percentages",
       y = "Points Scored",
       x = "Shots Attempted") +
  theme_minimal()


  
harden_plot
}

harden(100)
harden(200)
harden(500)
harden(1000)
harden(10000)
harden(100000)
```


### Kyrie Irving

```{r}
kyrie <- function(number_of_shots){

shot2 <- c(2, 0)
shot3 <- c(3, 0)

number_of_shots <- number_of_shots

kyrie2_prob <- c(0.575, 0.425)
kyrie3_prob <- c(0.398, 0.602)


kyrie2samp <- sample(shot2, size = number_of_shots, replace = TRUE, prob = kyrie2_prob)
kyrie3samp <- sample(shot3, size = number_of_shots, replace = TRUE, prob = kyrie3_prob)

kyrie2cumulative <- cumsum(kyrie2samp)
kyrie3cumulative <- cumsum(kyrie3samp)

# kyrie2cumulative
# kyrie3cumulative

shot_attempt <- seq(1, number_of_shots, by = 1)

kyrie2MaxPoints <- max(kyrie2cumulative)
kyrie3MaxPoints <- max(kyrie3cumulative)

kyrie2PointsPerShot <- max(kyrie2cumulative)/number_of_shots
kyrie3PointsPerShot <-max(kyrie3cumulative) / number_of_shots

kyrie_df <- data.frame(shot_attempt, kyrie2cumulative, kyrie3cumulative)
#kyrie_df

kyrie_plot <- ggplot()+
  geom_line(data = kyrie_df, aes(x = shot_attempt, 
                              y = kyrie2cumulative,
                              col = "2 point")) +
  geom_line(data = kyrie_df, aes(x = shot_attempt,
                              y = kyrie3cumulative,
                              col = "3 point")) +
  labs(title = "Kyrie Irving 2 Pointer v. 3 Pointer",
       subtitle = "By 2020-21 Shooting Percentages",
       y = "Points Scored",
       x = "Shots Attempted") +
  theme_minimal()

cat("Kyrie Irving would score", max(kyrie2cumulative), " points by 2 pointers only, and ", max(kyrie3cumulative), " points from only 3 pointers, based on  ", number_of_shots, "simmulated shot attempts.")
  
kyrie_plot
}

kyrie(100)
kyrie(200)
kyrie(500)
kyrie(1000)
kyrie(10000)
kyrie(100000)

```


### Trae Young

```{r}
trae <- function(number_of_shots){

shot2 <- c(2, 0)
shot3 <- c(3, 0)

number_of_shots <- number_of_shots

trae2_prob <- c(0.472, 0.528)
trae3_prob <- c(0.358, 0.642)


trae2samp <- sample(shot2, size = number_of_shots, replace = TRUE, prob = trae2_prob)
trae3samp <- sample(shot3, size = number_of_shots, replace = TRUE, prob = trae3_prob)

trae2cumulative <- cumsum(trae2samp)
trae3cumulative <- cumsum(trae3samp)



shot_attempt <- seq(1, number_of_shots, by = 1)

trae2MaxPoints <- max(trae2cumulative)
trae3MaxPoints <- max(trae3cumulative)

trae2PointsPerShot <- max(trae2cumulative)/number_of_shots
trae3PointsPerShot <-max(trae3cumulative) / number_of_shots

trae_df <- data.frame(shot_attempt, trae2cumulative, trae3cumulative)


trae_plot <- ggplot()+
  geom_line(data = trae_df, aes(x = shot_attempt, 
                              y = trae2cumulative,
                              col = "2 point")) +
  geom_line(data = trae_df, aes(x = shot_attempt,
                              y = trae3cumulative,
                              col = "3 point")) +
  labs(title = "Trae Young 2 Pointer v. 3 Pointer",
       subtitle = "By 2020-21 Shooting Percentages",
       y = "Points Scored",
       x = "Shots Attempted") +
  theme_minimal()

cat("Trae Young would score", max(trae2cumulative), " points by 2 pointers only, and ", max(trae3cumulative), " points from only 3 pointers, based on  ", number_of_shots, "simmulated shot attempts.")
  
trae_plot
}

trae(100)
trae(200)
trae(500)
trae(1000)
trae(10000)
trae(100000)


```


## Luka Doncic

```{r}
luka <- function(number_of_shots){

shot2 <- c(2, 0)
shot3 <- c(3, 0)

number_of_shots <- number_of_shots

luka2_prob <- c(0.564, 0.436)
luka3_prob <- c(0.364, 0.636)


luka2samp <- sample(shot2, size = number_of_shots, replace = TRUE, prob = luka2_prob)
luka3samp <- sample(shot3, size = number_of_shots, replace = TRUE, prob = luka3_prob)

luka2cumulative <- cumsum(luka2samp)
luka3cumulative <- cumsum(luka3samp)

# luka2cumulative
# luka3cumulative

shot_attempt <- seq(1, number_of_shots, by = 1)

luka2MaxPoints <- max(luka2cumulative)
luka3MaxPoints <- max(luka3cumulative)

luka2PointsPerShot <- max(luka2cumulative)/number_of_shots
luka3PointsPerShot <-max(lukacumulative) / number_of_shots

luka_df <- data.frame(shot_attempt, luka2cumulative, luka3cumulative)
#luka_df

luka_plot <- ggplot()+
  geom_line(data = luka_df, aes(x = shot_attempt, 
                              y = luka2cumulative,
                              col = "2 point")) +
  geom_line(data = luka_df, aes(x = shot_attempt,
                              y = luka3cumulative,
                              col = "3 point")) +
  labs(title = "Luka Donic 2 Pointer v. 3 Pointer",
       subtitle = "By 2020-21 Shooting Percentages",
       y = "Points Scored",
       x = "Shots Attempted") +
  theme_minimal()


  
luka_plot
}

luka(100)
luka(200)
luka(500)
luka(1000)
luka(10000)
luka(100000)
```

### Lamelo Ball

```{r}
lamelo <- function(number_of_shots){

shot2 <- c(2, 0)
shot3 <- c(3, 0)

number_of_shots <- number_of_shots

lamelo2_prob <- c(0.503, 0.497)
lamelo3_prob <- c(0.375, 0.625)


lamelo2samp <- sample(shot2, size = number_of_shots, replace = TRUE, prob = lamelo2_prob)
lamelo3samp <- sample(shot3, size = number_of_shots, replace = TRUE, prob = lamelo3_prob)



lamelo2cumulative <- cumsum(lamelo2samp)
lamelo3cumulative <- cumsum(lamelo3samp)

# lamelo2cumulative
# lamelo3cumulative



shot_attempt <- seq(1, number_of_shots, by = 1)

lamelo2MaxPoints <- max(lamelo2cumulative)
lamelo3MaxPoints <- max(lamelo3cumulative)

lamelo2PointsPerShot <- max(lamelo2cumulative)/number_of_shots
lamelo3PointsPerShot <-max(lamelo3cumulative) / number_of_shots

lamelo_df <- data.frame(shot_attempt, lamelo2cumulative, lamelo3cumulative)
#lamelo_df

lamelo_plot <- ggplot()+
  geom_line(data = lamelo_df, aes(x = shot_attempt, 
                              y = lamelo2cumulative,
                              col = "2 point")) +
  geom_line(data = lamelo_df, aes(x = shot_attempt,
                              y = lamelo3cumulative,
                              col = "3 point")) +
  labs(title = "Lamelo Ball 2 Pointer v. 3 Pointer",
       subtitle = "By 2020-21 Shooting Percentages",
       y = "Points Scored",
       x = "Shots Attempted") +
  theme_minimal()

cat("LaMelo Ball would score", max(lamelo2cumulative), " points by 2 pointers only, and ", max(lamelo3cumulative), " points from only 3 pointers, based on  ", number_of_shots, "simmulated shot attempts.")
  
lamelo_plot
}

lamelo(100)
lamelo(200)
lamelo(500)
lamelo(1000)
lamelo(10000)
lamelo(100000)
```



```{r}
#### type in the function name (at the top of each chunk above), which is a players name you would like,
#### in parenthesis include number of shots you would like to see simulated

### Example 10000 kevin durant simulations would be kd(10000)

##so

kd(10000)

## Will produce a graph that simulated 10000 kevin durant 2 and 3 pointers

```
### Players taking 100 shots

```{r}
kd(100)
steph(100)
dame(100)
lebron(100)
saddiq(100)
harden(100)
kyrie(100)
trae(100)
luka(100)
lamelo(100)

```

### Players taking 200 shots

```{r}
kd(200)
steph(200)
dame(200)
lebron(200)
saddiq(200)
harden(200)
kyrie(200)
trae(200)
luka(200)
lamelo(200)
```

### Players taking 500 shots

```{r}
kd(500)
steph(500)
dame(500)
lebron(500)
saddiq(500)
harden(500)
kyrie(500)
trae(500)
luka(500)
lamelo(500)
```

### Players taking 1,000 shots

```{r}
kd(1000)
steph(1000)
dame(1000)
lebron(1000)
saddiq(1000)
harden(1000)
kyrie(1000)
trae(1000)
luka(1000)
lamelo(1000)
```

### Players taking 10,000 shots

```{r}
kd(10000)
steph(10000)
dame(10000)
lebron(10000)
saddiq(10000)
harden(10000)
kyrie(10000)
trae(10000)
luka(10000)
lamelo(10000)
```

### Players Taking 100000 shots

```{r}
kd(100000)
steph(100000)
dame(100000)
lebron(100000)
saddiq(100000)
harden(100000)
kyrie(100000)
trae(100000)
luka(100000)
lamelo(100000)
```

